Training/task9 database storage
Asim-Khaleel/Training pull request #9
Opened 2023-12-05 10:43 UTC by Asim-Khaleel

Pull Request for [Task 9: Database storage](https://dev.azure.com/CodeNinjaConsulting/Talent%20Pool/_workitems/edit/1652/)

2023-12-06 11:10 UTC, sikandar-codeninja requested changes

2023-12-06 11:10 UTC, sikandar-codeninja commented on PageEdit/PageEdit.css
> +}
[suggestion] by convention, the keyframes class comes under the class that has animation set to these keyframes. e.g move this class below your loader class for better readability

2023-12-06 11:10 UTC, sikandar-codeninja commented on database_Storage/controllers/experienceController.js
> +  const experiences = await Experience.find();
add an empty object (empty filter here) as per mongoose documentation. [See here](https://mongoosejs.com/docs/api/model.html#Model.find())

2023-12-06 11:10 UTC, sikandar-codeninja commented on database_Storage/controllers/experienceController.js
> +
this is a bug here. for example if u added an experience item with description "ABC", then removed the description i.e its an empty string now, the update request will succede but the description will default back to ABC

2023-12-07 10:30 UTC, Asim-Khaleel commented on PageEdit/PageEdit.css
> +}
Yes, It makes more sense as you suggested. implemented, Thank you

2023-12-07 10:30 UTC, Asim-Khaleel commented on database_Storage/controllers/experienceController.js
> +  const experiences = await Experience.find();
I have added an empty as you suggested, Thank you

2023-12-07 10:33 UTC, Asim-Khaleel commented on database_Storage/controllers/experienceController.js
> +
There are already some checks handled on the frontend which do not allow any of the fields to be empty as I have used the same file for client side validation as well.

2023-12-08 06:51 UTC, sikandar-codeninja commented on database_Storage/controllers/experienceController.js
> +
well if all the fields are set mandatory and cant be empty then this will work. no need to change it then.

2023-12-08 06:52 UTC, sikandar-codeninja approved these changes

2023-12-08 07:41 UTC, merged